countries = ['India', 'Germany', 'France', 'Thailand', 'Georgia']
print(countries)
print(sorted(countries))
print(countries)
x = sorted(countries)
x.reverse()
print(x)
print(countries)
countries.reverse()
print(countries)
countries.reverse()
print(countries)
countries.sort()
print(countries)
countries.sort(reverse=True)
print(countries)